version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "ci"

  # Keep root Node.js dependencies up to date
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"

  # Keep dependencies in each package up to date
  - package-ecosystem: "npm"
    directory: "/packages/editor-core"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/packages/editor-render"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/packages/editor-media"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/packages/editor-ai"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/packages/editor-captions"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/packages/editor-shorts"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/packages/editor-plugins"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/packages/editor-ui"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"

  # Keep dependencies in apps up to date
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/apps/desktop"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
